FROM openjdk:17-alpine
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} CustomerService-0.0.1.jar
ENTRYPOINT ["java","-jar", "-XX:TieredStopAtLevel=1", "-noverify", "-Dspring.profiles.active=prod","/CustomerService-0.0.1.jar"]